# [バージョン管理ファイル]
# 仕様: https://github.com/cosomil/ver

name = ""
version = ""
sha256 = ""

# 追加でバージョン管理対象から除外したいファイル名のパターン（正規表現）を追加することができます
exclude_patterns = []
# デフォルトで除外されるパターンを無効化するかどうかを設定することができます
no_default_exclude_patterns = false

# metaテーブルには任意のメタデータを記録することができます
[meta]
